### ISSUE TITLE
libreddit: missing acct-user and acct-group

### ISSUE THREAD

**Issue by MrRoy** [r7l/r7l-overlay#2]
Hello,

I tried to emerge www-apps/libreddit, but the overlay is missing the acct-user and acct-group packages for this ebuild.

**Comment by r7l** [comment]
Hello, you're actually right. Still had them in my test overlay and as it seems, i've forgotten to move them into this one. It should be ok now. If you have any further issues, don't hesitate to report them.

**Comment by MrRoy** [comment]
Thanks !

**Comment by MrRoy** [comment]
@r7l do you have an init script for libreddit? If not, I'll make one and submit a pull request
(didn't want to open a new issue for this question)

**Comment by r7l** [comment]
@MrRoy No, i don't have one and a PR is more then welcome. I am using [S6](https://www.skarnet.org/software/s6/) to start it but i might also go on and make sure the systemd files are properly installed and working.
