### ISSUE TITLE
obsidian bump

### ISSUE THREAD

**Issue by ghost** [r7l/r7l-overlay#6]
hello, thank you for your hardwork! they've released new version.
https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.5/obsidian_1.4.5_amd64.deb

**Comment by r7l** [comment]
@toprak Thanks. I've bumped it and even took the time to clean the Ebuild file a bit. I've moved Obsidian but it shouldn't bother you when updating. If you ran into any issue, don't hesitate to report back.
