### ISSUE TITLE
kyocera-universal-driver can't be installed

### ISSUE THREAD

**Issue by RaphaelNeubert** [r7l/r7l-overlay#8]
Hi,
the kyocera-universal-driver depends  on  <dev-python/pypdf-4.0 but the gentoo repository only offers the pypdf-4.2.0, 
therefore kyocera-universal-driver can't be installed using this ebuild. 

I'm not really sure how we can fix this since PyPDF3 seems to be a required dependency as seen 
inside the .deb's postinstall script.  
```
install_pypdf(){
    if [ -f /usr/bin/python3 ]; then
        if python3 -c 'import PyPDF3' 2> /dev/null ; then
            #echo "PyPDF found"
            true
        else 
            cd $PYTHON_DIRECTORY/PyPDF3-1.0.1/ || exit
            python3 setup.py install
        fi
    else
        if python -c 'import PyPDF3' 2> /dev/null ; then
            #echo "PyPDF found"
            true
        else 
            cd $PYTHON_DIRECTORY/PyPDF3-1.0.1/ || exit
            python setup.py install
        fi
    fi
}

```

Maybe the Fedora or OpenSUSE version is already using v4...

**Comment by r7l** [comment]
Thanks for the report. I didn't notice as i've the driver installed and Portage never complained. I've just added the old package to my repo. Can you give it a try and report back if it helps? I've tested the package and it works for me.

From what i can see, there is no new version of this driver and the version in Arch Linux also uses PyPDF 3.x.

Whenever i notice a new version of this driver, i may try using PyPDF 4.x.

**Comment by RaphaelNeubert** [comment]
That was quick.  
It works! Not sure if pypdf-3.17.4 needs to me marked as unstable since it used to be the stable version:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=64eb742f9cec5b463e926f9bfd7fb67b251e8332

Thank you very much.

**Comment by buzden** [comment]
@r7l Do you know if it's possible to either make old `pypdf` version work with Python 3.13 or to make `kyocera-universal-driver` to work with newer `pypdf`? For now, this old `pypdf` is the only package that required Python 3.12 to be installed on my machine and I wonder if it's really needed.
